### ISSUE TITLE
Sometimes fails to sync pull request branch after force push

### ISSUE THREAD

**Issue by tdb** [brndnmtthws/labhub#10]
On some occasions when I force push to a branch for a pull request it doesn't trigger a pipeline. On the LabHub console I see:

```
Error: Caught error handling PR: GitError { message: "Git error: \"cannot push non-fastforwardable reference\"" }
```

Does it need to force push branches from GitHub to GitLab? I am puzzled why this doesn't happen every time though.

**Comment by brndnmtthws** [comment]
Hmm, I think it needs to be force pushed. It should be fixed by prefixing the push ref with a `+`, here: https://github.com/brndnmtthws/labhub/blob/master/src/github.rs#L204

See: https://git-scm.com/book/en/v2/Git-Internals-The-Refspec

I'll put together a patch in a little bit.
