### ISSUE TITLE
pipeline is to often triggered

### ISSUE THREAD

**Issue by psychocoderHPC** [brndnmtthws/labhub#107]
First, thanks for this nice bot.

I realized that our gitlab CI pipeline is triggered each time I change e.g. the title of a pull request or assign a developer to the request.

This behavior is coming from the grouped github events for `Pull request`. It is in github not possible to set events only for `Pull request opened" and `Pull updated`(hash changed)

github configuration for webhooks:
![github_pull](https://user-images.githubusercontent.com/4037125/66987778-a76fff00-f0c1-11e9-90e0-bafd44c41769.png)

Is it possible to update the bot that a pipe is only triggered when the pull request is opened or updated (e.g. forcepush or new commits)?

CC-ing: @SimeonEhrig

**Comment by tobiashuste** [comment]
@christianhueserhzdr was so nice to have a look into this. He will submit a PR for that. In the meantime, we run with the implementation from this repository: https://github.com/hzdr/labhub

**Comment by brndnmtthws** [comment]
Hopefully #128 resolves this for you.
